// Stage 8 — turn an approved skill into a SKILL.md on disk, ready to publish.

import { mkdir, writeFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

export function slugify(text, fallback = 'skill') {
  const slug = String(text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)
    .replace(/-+$/g, '');
  return slug || fallback;
}

/** Frontmatter strings must not break the YAML block. */
function yamlSafe(text) {
  return String(text).replace(/\s+/g, ' ').replace(/"/g, "'").trim();
}

/**
 * The published file. Frontmatter carries the two fields an agent routes on;
 * provenance goes in the body so it survives being copied elsewhere.
 */
export function renderSkillMd(skill) {
  const { name, description, body, source, workflow, skill_score, review } = skill;

  const provenance = [
    '## Source',
    '',
    `Extracted from [${source.full_name}](${source.url})` +
      `${source.language ? ` (${source.language})` : ''}, ` +
      `${source.stars.toLocaleString()} stars.`,
    '',
    source.doc_files?.length
      ? `Documentation read: ${source.doc_files.map((f) => `\`${f}\``).join(', ')}.`
      : 'Documentation read: `README.md`.',
    '',
    workflow?.evidence ? `> ${workflow.evidence.replace(/\s+/g, ' ').trim()}` : '',
    '',
    `Generated by the ideafeed pipeline · rule score ${skill_score}` +
      `${review ? ` · reviewer ${review.verdict} (${review.quality})` : ''} · ` +
      `${new Date().toISOString().slice(0, 10)}`,
  ]
    .filter((line) => line !== undefined)
    .join('\n');

  return [
    '---',
    `name: ${name}`,
    `description: "${yamlSafe(description)}"`,
    '---',
    '',
    body.trim(),
    '',
    provenance,
    '',
  ].join('\n');
}

/**
 * Write a skill, avoiding collisions with skills already on disk.
 * Returns the slug actually used.
 */
export async function writeSkill(skillsDir, skill) {
  await mkdir(skillsDir, { recursive: true });

  let slug = slugify(skill.name);
  if (existsSync(join(skillsDir, slug))) {
    slug = `${slug}-${slugify(skill.source.owner).slice(0, 16)}`;
  }
  let attempt = 2;
  while (existsSync(join(skillsDir, slug))) {
    slug = `${slugify(skill.name)}-${attempt++}`;
  }

  const dir = join(skillsDir, slug);
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, 'SKILL.md'), renderSkillMd({ ...skill, name: slug }), 'utf8');
  return slug;
}

export async function listExistingSkills(skillsDir) {
  if (!existsSync(skillsDir)) return [];
  const entries = await readdir(skillsDir, { withFileTypes: true });
  return entries.filter((e) => e.isDirectory()).map((e) => e.name);
}
