// GENERATED by scripts/gen-themes.mjs — do not edit by hand.
// The picker's list, and the browser-chrome colour per palette. Full palettes
// live in design/themes.css; only what the UI needs to draw a swatch is
// duplicated here, and both come from the same table so they cannot disagree.

export interface PaletteFace {
  bg: string;
  panel: string;
  accent: string;
  text: string;
}

export interface Palette {
  key: string;
  label: string;
  blurb: string;
  light: PaletteFace;
  dark: PaletteFace;
}

export const PALETTES: Palette[] = [
  {
    key: 'porcelain',
    label: 'Porcelain',
    blurb: 'Warm paper and bronze — the house default',
    light: { bg: '#F4F3F0', panel: '#FEFEFE', accent: '#87671D', text: '#2B2922' },
    dark: { bg: '#0F0E0B', panel: '#211F19', accent: '#D7AA42', text: '#D9D6CE' },
  },
  {
    key: 'graphite',
    label: 'Graphite',
    blurb: 'Neutral grey under cool steel',
    light: { bg: '#F3F2F2', panel: '#FEFEFE', accent: '#465E81', text: '#272725' },
    dark: { bg: '#151514', panel: '#262524', accent: '#8BA1C1', text: '#DCDCDA' },
  },
  {
    key: 'lapis',
    label: 'Lapis',
    blurb: 'Deep imperial blue under roman gold',
    light: { bg: '#E9EBF1', panel: '#F8F9F9', accent: '#80641E', text: '#1D1F25' },
    dark: { bg: '#07090D', panel: '#151821', accent: '#D2A941', text: '#CCCED7' },
  },
  {
    key: 'slate',
    label: 'Slate',
    blurb: 'Cool grey and steel',
    light: { bg: '#F3F5F6', panel: '#FEFEFE', accent: '#2764A5', text: '#24282E' },
    dark: { bg: '#1F2329', panel: '#2D343C', accent: '#87B4E3', text: '#E8EAED' },
  },
  {
    key: 'forest',
    label: 'Forest',
    blurb: 'Deep green, sage highlight',
    light: { bg: '#EDF2F0', panel: '#FBFCFB', accent: '#2A794F', text: '#1F2824' },
    dark: { bg: '#0D120F', panel: '#1A2620', accent: '#59C58B', text: '#D1DBD7' },
  },
  {
    key: 'claret',
    label: 'Claret',
    blurb: 'Oxblood and old rose',
    light: { bg: '#ECE4E6', panel: '#F5F3F3', accent: '#8A283C', text: '#1F191A' },
    dark: { bg: '#1E1517', panel: '#312326', accent: '#DD8899', text: '#E4DDDE' },
  },
  {
    key: 'ink',
    label: 'Ink',
    blurb: 'Near-black paper, cold cyan',
    light: { bg: '#F7F8F8', panel: '#FEFEFE', accent: '#187A8B', text: '#282D2F' },
    dark: { bg: '#070808', panel: '#16191A', accent: '#33C2DB', text: '#CBD0D2' },
  },
  {
    key: 'navy',
    label: 'Navy',
    blurb: 'Naval blue with brass fittings',
    light: { bg: '#E6E9EF', panel: '#F5F6F7', accent: '#955718', text: '#1B1E22' },
    dark: { bg: '#090C10', panel: '#171C24', accent: '#DF8C3A', text: '#CED2D9' },
  },
  {
    key: 'plum',
    label: 'Plum',
    blurb: 'Aubergine and lilac',
    light: { bg: '#EFEAF0', panel: '#F9F8F9', accent: '#6F2D8F', text: '#241D25' },
    dark: { bg: '#1F1721', panel: '#312535', accent: '#C28FDC', text: '#E5E0E6' },
  },
  {
    key: 'moss',
    label: 'Moss',
    blurb: 'Olive and cream, field-notes green',
    light: { bg: '#E7EAE1', panel: '#F2F3F0', accent: '#427321', text: '#1B1D16' },
    dark: { bg: '#13150F', panel: '#25281D', accent: '#85CE55', text: '#DBDDD4' },
  },
  {
    key: 'copper',
    label: 'Copper',
    blurb: 'Oxidised metal, warm and worked',
    light: { bg: '#E9E2DD', panel: '#F0EEED', accent: '#884620', text: '#1A1614' },
    dark: { bg: '#1C1612', panel: '#2F2620', accent: '#DB9166', text: '#E2DDDA' },
  },
  {
    key: 'teal',
    label: 'Teal',
    blurb: 'Deep teal cut with coral',
    light: { bg: '#F0F4F5', panel: '#FEFEFE', accent: '#A13E26', text: '#222A2B' },
    dark: { bg: '#182325', panel: '#263739', accent: '#E6A494', text: '#E5EAEB' },
  },
  {
    key: 'iris',
    label: 'Iris',
    blurb: 'Indigo and periwinkle',
    light: { bg: '#EDECF3', panel: '#FBFBFC', accent: '#3F2999', text: '#211F28' },
    dark: { bg: '#0D0C13', panel: '#1B1927', accent: '#9886DF', text: '#D3D1DB' },
  },
  {
    key: 'arctic',
    label: 'Arctic',
    blurb: 'Ice white over deep polar blue',
    light: { bg: '#F6F8F9', panel: '#FEFEFE', accent: '#2174B0', text: '#262D31' },
    dark: { bg: '#202C32', panel: '#2D3E46', accent: '#8BC2E9', text: '#F4F5F6' },
  },
  {
    key: 'ember',
    label: 'Ember',
    blurb: 'Charcoal with a live coal in it',
    light: { bg: '#E3DFDD', panel: '#EEECEA', accent: '#8C3217', text: '#161412' },
    dark: { bg: '#0B0A09', panel: '#1D1A18', accent: '#E27250', text: '#D6D0CD' },
  },
  {
    key: 'mono',
    label: 'Mono',
    blurb: 'Pure greyscale — the accent is the ink',
    light: { bg: '#F5F5F5', panel: '#FEFEFE', accent: '#666666', text: '#292929' },
    dark: { bg: '#080808', panel: '#181818', accent: '#919191', text: '#CFCFCF' },
  },
  {
    key: 'sand',
    label: 'Sand',
    blurb: 'Desert paper, dusty blue accent',
    light: { bg: '#EDE9E3', panel: '#F5F4F3', accent: '#345C7F', text: '#1F1D19' },
    dark: { bg: '#28231A', panel: '#3D3527', accent: '#9ABAD6', text: '#EDEBE8' },
  },
  {
    key: 'rose',
    label: 'Rose',
    blurb: 'Grey with dusty pink',
    light: { bg: '#F1EEEF', panel: '#FCFBFB', accent: '#8F324E', text: '#272123' },
    dark: { bg: '#322A2D', panel: '#43393D', accent: '#E3B0BF', text: '#F8F7F7' },
  },
  {
    key: 'pine',
    label: 'Pine',
    blurb: 'Black-green and pale gold',
    light: { bg: '#E0EBE8', panel: '#F0F3F2', accent: '#716914', text: '#161D1B' },
    dark: { bg: '#080D0B', panel: '#15211E', accent: '#DCCE38', text: '#CCD7D4' },
  },
  {
    key: 'oxide',
    label: 'Oxide',
    blurb: 'Iron grey and rust',
    light: { bg: '#E0DDDC', panel: '#EBE9E8', accent: '#7D3D21', text: '#131111' },
    dark: { bg: '#292524', panel: '#3A3534', accent: '#E1A78E', text: '#EEEDEC' },
  },
];

export const DEFAULT_PALETTE = 'ink';

export const paletteByKey = (key: string): Palette =>
  PALETTES.find((p) => p.key === key) ?? PALETTES.find((p) => p.key === DEFAULT_PALETTE)!;
